#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^fcash:" ; then
    echo "Creating system group: fcash"
    groupadd --system fcash
fi

# add user
if ! getent passwd | grep -q "^fcash:"; then
    echo "Creating fcash system user"
    useradd --gid "fcash" --system -m fcash
fi

# build nodejs addons
cd "/usr/opt/fcash"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/fcash/.fcash/data"
chown -R fcash:fcash "/home/fcash/.fcash"

# start fcash
if hash service 2> /dev/null; then
    service fcash start || echo "fcash could not be registered or started"
elif hash start 2> /dev/null; then
    start fcash || echo "fcash could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "fcash.service" && \
            systemctl start "fcash.service"
    } || echo "fcash could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so fcash could not be started'
fi
